spring:
  application:
    name: spring-boot-graphql-chapter3

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphqls
        variables: classpath:playground/bank_account_variables.json
    # enabled: false