spring:
  application:
    name: spring-boot-graphql-chapter6
  servlet:
    multipart:
      max-file-size: 5MB

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: true
  playground:
    headers:
      Authorization: Bearer 0c2b39f0-429b-4daf-b83d-fcb101d69a80
      user_id: 2840d5fe-4d4d-412c-903f-1b0d71119f5e
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphqls
        variables: classpath:playground/bank_account_variables.json
    # enabled: false

# voyager:
  # enabled: false